# Generated by Django 5.1.1 on 2024-09-14 02:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
        ('centers', '0001_initial'),
        ('collaborators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_protocolo', models.CharField(blank=True, editable=False, max_length=7, unique=True, verbose_name='Contrato')),
                ('data_assinatura', models.DateField(blank=True, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('valor_contrato', models.DecimalField(decimal_places=2, max_digits=10)),
                ('natureza_pagamento', models.CharField(choices=[('PAGAMENTO ÚNICO', 'PAGAMENTO ÚNICO'), ('PAGAMENTO ANUAL', 'PAGAMENTO ANUAL'), ('PAGAMENTO SEMANAL', 'PAGAMENTO SEMANAL'), ('PAGAMENTO MENSAL', 'PAGAMENTO MENSAL'), ('PAGAMENTO QUIZENAL', 'PAGAMENTO QUINZENAL'), ('PAGAMENTO TRIMESTRAL', 'PAGAMENTO TRIMESTRAL'), ('PAGAMENTO SEMESTRAL', 'PAGAMENTO SEMESTRAL'), ('PAGAMENTO SOB DEMANDA', 'PAGAMENTO SOB DEMANDA')], max_length=30)),
                ('fiscal_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_fiscal_principal', to='collaborators.colaborador', verbose_name='Fiscal Principal')),
                ('fiscal_substituto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_fiscal_substituto', to='collaborators.colaborador', verbose_name='Fiscal Substituto')),
            ],
        ),
        migrations.CreateModel(
            name='Aditivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('justificativa', models.CharField(max_length=150)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aditivos', to='contracts.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='LinhaOrcamentaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(blank=True, choices=[('OPEX', 'OPEX'), ('CAPEX', 'CAPEX')], max_length=100, null=True, verbose_name='Tipo de linha')),
                ('custo_despesa', models.CharField(choices=[('A', 'Base Principal'), ('B', 'Serviços Especializados'), ('C', 'Despesas Compartilhadas')], max_length=100, verbose_name='CUSTO/DESPESA')),
                ('descricao_resumida', models.CharField(blank=True, max_length=255, null=True, verbose_name='Finalidade')),
                ('objeto', models.CharField(blank=True, max_length=80, null=True, verbose_name='Objeto')),
                ('classificacao_orcamento', models.CharField(blank=True, choices=[('NOVO', 'NOVO'), ('RENOVAÇÃO', 'RENOVAÇÃO'), ('CARY OVER', 'CARY OVER'), ('REPLANEJAMENTO', 'REPLANEJAMENTO'), ('N/A', 'N/A')], max_length=100, null=True)),
                ('tipo_contrato', models.CharField(blank=True, choices=[('SERVIÇO', 'SERVIÇO'), ('FORNECIMENTO', 'FORNECIMENTO'), ('ASSINATURA', 'ASSINATURA'), ('FORNECIMENTO/SERVIÇO', 'FORNECIMENTO/SERVIÇO')], max_length=100, null=True)),
                ('status_linha_orcamentaria', models.CharField(blank=True, choices=[('I', 'SERVIÇO'), ('II', 'FORNECIMENTO'), ('III', 'ASSINATURA'), ('IV', 'FORNECIMENTO/SERVIÇO')], max_length=100, null=True)),
                ('tipo_provavel_contratacao', models.CharField(choices=[('A', 'LICITAÇÃO'), ('B', 'DISPENSA EM RAZÃO DO VALOR'), ('C', 'CONVÊNIO'), ('D', 'FUNDO FIXO'), ('E', 'INEXIGIBILIDADE'), ('F', 'ATA DE REGISTRO DE PREÇO'), ('H', 'ACORDO DE COOPERAÇÃO'), ('I', 'APOSTILAMENTO')], max_length=100)),
                ('valor_orcado', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('status_elaboracao_tr', models.CharField(blank=True, choices=[('VENCIDO', 'VENCIDO'), ('DENTRO DO PRAZO', 'DENTRO DO PRAZO'), ('ELABORADO COM ATRASO', 'ELABORADO COM ATRASO'), ('ELABORADO NO PRAZO', 'ELABORADO NO PRAZO')], max_length=100, null=True)),
                ('necessidade_contratacao', models.DateField(blank=True, null=True)),
                ('status_processo', models.CharField(blank=True, choices=[('I', 'PLANEJAMENTO'), ('II', 'Execução'), ('III', 'Elaboração de TR'), ('IV', 'Cotação'), ('V', 'Em proc. aditivo')], max_length=100, null=True)),
                ('status_contratacao', models.CharField(blank=True, choices=[('A', 'DENTRO DO PRAZO'), ('B', 'CONTRATADO NO PRAZO'), ('C', 'CONTRATADO COM ATRASO'), ('D', 'PRAZO VENCIDO'), ('E', 'LINHA TOTALMENTE REMANEJADA'), ('F', 'LINHA TOTALMENTE EXECUTADA'), ('G', 'LINHA DE PAGAMENTO'), ('H', 'LINHA PARCIALMENTE REMANEJADA'), ('I', 'LINHA PARCIALMENTE EXECUTADA'), ('J', 'N/A')], max_length=100, null=True)),
                ('obs_contrato', models.TextField(blank=True, max_length=400, null=True)),
                ('ano_orcamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='budgets.orcamento')),
                ('centro_custo_gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centers.centrodecustogestor')),
                ('centro_custo_solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centers.centrodecustosolicitante')),
                ('possivel_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_fiscal_possivel', to='collaborators.colaborador', verbose_name='Fiscal')),
            ],
            options={
                'verbose_name': 'Linha Orçamentária',
                'verbose_name_plural': 'Linhas Orçamentárias',
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='linha_orcamentaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='contracts.linhaorcamentaria'),
        ),
        migrations.CreateModel(
            name='Prestacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.PositiveIntegerField(editable=False)),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Remanejamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('data_remanejamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo', models.TextField()),
                ('linha_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remanejamentos_destino', to='contracts.linhaorcamentaria')),
                ('linha_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remanejamentos_origem', to='contracts.linhaorcamentaria')),
            ],
            options={
                'verbose_name': 'Remanejamento',
                'verbose_name_plural': 'Remanejamentos',
            },
        ),
    ]
