# Generated by Django 5.1.1 on 2024-09-12 13:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_prestacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remanejamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('data_remanejamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo', models.TextField()),
                ('linha_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remanejamentos_destino', to='contracts.linhaorcamentaria')),
                ('linha_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remanejamentos_origem', to='contracts.linhaorcamentaria')),
            ],
            options={
                'verbose_name': 'Remanejamento',
                'verbose_name_plural': 'Remanejamentos',
            },
        ),
    ]
