# Generated by Django 5.1.1 on 2024-09-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auxiliocolaborador',
            name='previsao_inicio',
            field=models.DateField(blank=True, default='2024-09-16', null=True),
        ),
    ]
