# Generated by Django 5.1.1 on 2024-09-11 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0001_initial'),
        ('budgets', '0002_alter_orcamento_classe'),
        ('collaborators', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='auxiliocolaborador',
            unique_together={('beneficiado', 'orcamento', 'tipo', 'beneficio')},
        ),
    ]
