# Generated by Django 5.1.1 on 2024-09-14 02:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('classe', models.CharField(blank=True, choices=[('OPEX', 'OPEX'), ('CAPEX', 'CAPEX')], max_length=100, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.centrodecustogestor')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'unique_together': {('ano', 'centro', 'classe')},
            },
        ),
        migrations.CreateModel(
            name='OrcamentoExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('centro', models.CharField(max_length=20)),
                ('classe', models.CharField(blank=True, choices=[('OPEX', 'OPEX'), ('CAPEX', 'CAPEX')], max_length=100, null=True)),
                ('tipo_movimentacao', models.CharField(choices=[('entrada', 'Entrada'), ('retirada', 'Retirada')], max_length=8)),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos_externos', to='budgets.orcamento')),
            ],
            options={
                'verbose_name': 'Orçamento Externo',
                'verbose_name_plural': 'Orçamentos Externos',
            },
        ),
    ]
